### ISSUE TITLE
'Update failed!'

### ISSUE THREAD

**Issue by yesmadam01** [vantuan88291/react-native-ota-hot-update#3]
i am pull the code and run then. show error
<img width="400" alt="Screenshot 2024-11-05 at 1 40 07 PM" src="https://github.com/user-attachments/assets/5e884f95-1264-4dd5-bfe9-daf34c93c123">

**Comment by vantuan88291** [comment]
Hi, it not an issue, because I have changed the bundle file of the other app on firebase store demo project that I have uploaded before. So you might need to setup firebase store by your own

**Comment by yesmadam01** [comment]
thanks its working

**Comment by vantuan88291** [comment]
> @vantuan88291 when i build a new version with text 'hello 3' for version 4, but when I update a new ver 4, my text is not update, I can hot update when I am debug my app

Please ensure the bundle file that the app downloaded is correct, in debug mode will not working

**Comment by HongQuang231** [comment]
@vantuan88291 how can i check it in debug mode? if release app to testfight, the module can working????
