### ISSUE TITLE
Method setupBundlePath doesn't work on Android.

### ISSUE THREAD

**Issue by agassi70** [vantuan88291/react-native-ota-hot-update#4]
I tried on android phone using setupBundlePath method and got error. Row 99 in HotUpdateModule.java - Log.d("setupBundlePath: ", fileUnzip), because of fileUnzip == null. Then I looked at the code in the setupBundlePath method and realized that it was not working. A lot of syntax errors. You need to fix this method.

**Comment by vantuan88291** [comment]
Hi, thank for your report. setupBundlePath function need pass path parameter. Did you verify the path of zip file is exist or valid? if exist need file path valid, the zip file should be generated from script that I provided in the document.
About the syntax errors, please feel free to create a Pull request. Thanks

**Comment by agassi70** [comment]
I use only this method setupBundlePath and download file from not public  Google cloud storage bucket using Google Functions. Probably I got incorrect zip file in my app.  I fixed my Function and now I get correct zip file and all works without errors. Thank you!

But what about strange syntax in unzip method:
try (InputStream is = new FileInputStream(zipFile);
             ZipInputStream zis = new ZipInputStream(is)) {.....
             and
try (OutputStream os = new FileOutputStream(newFile)) { .....

As I know must be - try {...} catch(e) {}.

Or maybe my knowledge is outdated?

**Comment by vantuan88291** [comment]
> I use only this method setupBundlePath and download file from not public Google cloud storage bucket using Google Functions. Probably I got incorrect zip file in my app. I fixed my Function and now I get correct zip file and all works without errors. Thank you!
> 
> But what about strange syntax in unzip method: try (InputStream is = new FileInputStream(zipFile); ZipInputStream zis = new ZipInputStream(is)) {..... and try (OutputStream os = new FileOutputStream(newFile)) { .....
> 
> As I know must be - try {...} catch(e) {}.
> 
> Or maybe my knowledge is outdated?

Hi, for try catch syntax you can refer here, that from java 7: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
