### ISSUE TITLE
update fail in my app

### ISSUE THREAD

**Issue by HongQuang231** [vantuan88291/react-native-ota-hot-update#5]
i add lib to my project, i release to testfilght, and i store my zip file in google drive, in debug mode, it can download but when i download app from testfilght, it alert update fail

link download : https://drive.google.com/uc?export=download&id=1Y0pjzdI8qZsTm1MiyM90H21WF66Ac2-y

**Comment by tuanlevi95** [comment]
Bạn ơi google drive không cho phép download dạng stream trực tiếp đâu, bạn tải về chắc được file html thì báo fail là đúng rồi đó. Bạn phải store bundle file lên host nào đó cho download trực tiếp thì mới được, ví dụ như firebase storage, hoặc server của bạn

**Comment by HongQuang231** [comment]
@tuanlevi95 mình có dùng link như trên kia thì thấy click nó download file zip về, mình nghĩ cơ chế nó cũng sẽ download về giống nhau chứ nhỉ

**Comment by tuanlevi95** [comment]
click download là nó xử lý 1 đoạn ở trình duyệt rồi direct sang streaming url rồi b, còn download trong app thì ko làm thế dc đâu, làm dc thế thì dùng gg drive lưu bản update đã ngon quá. Mình check có lib download dc google drive nhưng phải có login các thứ: https://github.com/RobinBobin/react-native-google-drive-api-wrapper/blob/master/src/README.md

**Comment by HongQuang231** [comment]
nhưng khi mình chạy mode debug trên máy ảo thì nó download success, nhưng cứ đẩy app lên testfight, thì lại báo update fail
