### ISSUE TITLE
Error: 'RNRNhotupdateSpec.h' file not found in react-native v0.76.1

### ISSUE THREAD

**Issue by caothuyen** [vantuan88291/react-native-ota-hot-update#6]
i install in react-native v0.76.1

**Comment by vantuan88291** [comment]
let me try and fix on rn 0.76

**Comment by tuanlevi95** [comment]
seem 0.76 enable new arch by default, this lib has not supported new arch just yet, you can temporarily disable new arch first and try

**Comment by caothuyen** [comment]
It seems that disable new arch works, but do you plan when to support new arch, because I updated rn 0.76 to have this feature

**Comment by vantuan88291** [comment]
> It seems that disable new arch works, but do you plan when to support new arch, because I updated rn 0.76 to have this feature

I am working on it and will release new version for new architecture soon. Tis

**Comment by aderiushev** [comment]
@vantuan88291 thanks for working on it! we're migrating off from codepush/expo so would be nice to have those changes implemented soon, from my end i can contribute to the client part (not native, unfortunately)

thank you again, looking forward

**Comment by vantuan88291** [comment]
New version supported for new arch is published: 2.0.1
