### ISSUE TITLE
Failing update App

### ISSUE THREAD

**Issue by ambatukarimba** [vantuan88291/react-native-ota-hot-update#7]
JavaMethodWrapper.invoke
com.facebook.react.bridge.NativeArgumentsParseException - RNhotupdate.setupBundlePath got 3 arguments, expected 4

> const downloadBundle = async () => {
>         const apiUrl  = process.env.API_URL;
>         fetch(apiUrl+'/ota/update.json')
>             .then(response => response.json()) 
>             .then(data => {
>                 const url = data.downloadAndroidUrl;
>                 const version = data.version;
>                 hotUpdate.downloadBundleUri(ReactNativeBlobUtil, url, version, {
>                     updateSuccess: () => {
>                         hotUpdate.setCurrentVersion(version);
>                         AsyncStorage.setItem('lastUpdate', new Date().toLocaleString());
>                     },
>                     updateFail(message?: string) {
>                         Alert.alert('Update failed!', message, [
>                           {
>                             text: 'Cancel',
>                             onPress: () => console.log('Cancel Pressed'),
>                             style: 'cancel',
>                           },
>                         ]);
>                       },
>                     restartAfterInstall: true,
>                     progress: (received: string, total: string) => {
>                         const receivedNum = parseFloat(received);
>                         const totalNum = parseFloat(total);
>                         const percentage = receivedNum / totalNum;
>                         const receivedSize = (receivedNum / 1024 / 1024).toFixed(2);
>                         const totalSize = (totalNum / 1024 / 1024).toFixed(2);
>                         setReceivedSize(receivedSize);
>                         setTotalSize(totalSize);
>                         setProgress(percentage);
>                     }
>                 });
>             })
>             .catch(error => {
>                 ToastAndroid.show('Gagal memeriksa versi terbaru :' +error, ToastAndroid.SHORT);
>             });
>     }

> Fatal Exception: com.facebook.react.bridge.NativeArgumentsParseException: RNhotupdate.setupBundlePath got 3 arguments, expected 4
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:297)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:19)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
       at java.lang.Thread.run(Thread.java:1012)
      <

**Comment by vantuan88291** [comment]
Hi, may I know what is the react native version, and what is the version of rn hot update did you use?

**Comment by ambatukarimba** [comment]
> Hi, may I know what is the react native version, and what is the version of rn hot update did you use?

i'm use this latest version of rn hot update.
{
"react-native": "0.74.3",
"react-native-ota-hot-update": "^1.1.2",
}

**Comment by vantuan88291** [comment]
`RNhotupdate.setupBundlePath got 3 arguments, expected 4`
this is so weird, setupBundlePath function just need 2 parameters, as you can see on android module, can you help me to debug that function and see what are parameters pass to it? thanks

**Comment by tuanlevi95** [comment]
btw no need this: 
`hotUpdate.downloadBundleUri(ReactNativeBlobUtil, url, version, {
updateSuccess: () => {
hotUpdate.setCurrentVersion(version);
AsyncStorage.setItem('lastUpdate', new Date().toLocaleString());
},`

can remove hotUpdate.setCurrentVersion(version); because it already save from native module when download success
