### ISSUE TITLE
No changes in code for IOS after successful bundle update

### ISSUE THREAD

**Issue by agassi70** [vantuan88291/react-native-ota-hot-update#8]
I created builds and distribute their on the Firebase distribution. File  versions.json was stored on Google cloud bucket.
Then I made index.android.bundle.zip and main.bundle.zip and upload their also to Google cloud bucket. 
Then changed file versions.json.

Results:
Android - All alerts worked successfully and I see that my app created a new path for bundle js. After reloading app I see changes from new bundle.

IOS - All alerts worked successfully and I see that my app created a new path for bundle js. After reloading app I don't see any changes from new bundle. All works without errors, but it seems app continue to use default path for js bundle.

**Comment by vantuan88291** [comment]
Can you share your code here? The way from download the bundle

**Comment by agassi70** [comment]
I do it in redux saga:

import {FileSystem, Dirs} from "react-native-file-access";
import hotUpdate from 'react-native-ota-hot-update';

...

export function* updateBundle(newVersion) {
  try {
    const bundleName = "main.bundle";

// fetch from bucket to `${Dirs.DocumentDir}/${bundleName}` 
    const {status} = yield FileSystem.fetch(
      `https://us-central1-project.cloudfunctions.net/jsbundle/bundle/${Platform.OS}`,
      {method: "GET", path: `${Dirs.DocumentDir}/${bundleName}`}
    );

    if (status === 200) {
      const result = yield hotUpdate.setupBundlePath(`${Dirs.DocumentDir}/${bundleName}`);
      if (result) {
        yield hotUpdate.setCurrentVersion(Number(newVersion));
        yield delay(300);
        yield hotUpdate.resetApp();
      }
    }
  } catch (err) {
    console.log(err.message);
  }
}

All works correctly,  I used next debug:
FileSystem.ls(`${Dirs.DocumentDir}/main.unzip`) -> ["output"]
FileSystem.ls(`${Dirs.DocumentDir}/main.unzip/output`) ->  ["main.jsbundle", "assets"]
...assets ->  ["main.jsbundle", "assets"] -> ["node_modules", "src"]

**Comment by vantuan88291** [comment]
hmm so weird, you can try the demo project and it work correctly, is there something wrong with your ios bundle?

Can you try to use hotUpdate.downloadBundleUri instead of FileSystem.fetch and setupBundlePath? if it work maybe issue come from setupBundlePath, tis

**Comment by agassi70** [comment]
I also tried :

hotUpdate.downloadBundleUri(ReactNativeBlobUtil, `us-central1-project.cloudfunctions.net/jsbundle/bundle/${Platform.OS}`, newVersion, {
      updateSuccess: () => {
        console.log('update success!');
      },
      updateFail: (message) => {
        Alert.alert('Update failed!', message, [
          {
            text: 'Cancel',
            onPress: () => console.log('Cancel Pressed'),
            style: 'cancel',
          },
        ]);
      },
      restartAfterInstall: true,
    });

And alert  bundlepath from  index.tsx in your npm module after next sting:
const path = await downloadBundleFile(downloadManager, uri, option?.headers, option?.progress);

I got path: var/mobile/Containers/Data/Application/...hash.../Documents/ReactNativeBlobUtil_tmp/ReactNativeBlobUtil-Tmp_qd84......

And effect the same - I don't see changes and it seems app continue to use default path for js bundle.

**Comment by agassi70** [comment]
I also thought about this code:

#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [RNhotupdate getBundle]; ## add this line
#endif

I use fastlane for creating build (command build_ios_app with configuration "Release"). 
But when app gets condition DEBUG (I thought only on local build in simulator)? 
How to check this condition?

**Comment by vantuan88291** [comment]
Oh so you can try to run your code using xcode first, with release mode and see it work or not, can try con simulator, just set schema run is release from xcode and try. The condition debug when you run on debug mode.

**Comment by agassi70** [comment]
Yes. I tried via Xcode and updating is working. Then I refactored my CI/CD, add needed schema in Fastlane command. After that updating works test builds.

**Comment by agassi70** [comment]
Be sure, that you use Release scheme.
